### ISSUE TITLE
Building failed

### ISSUE THREAD

**Issue by XahidEx** [delbaoliveira/website#23]
Please fix this error. I liked this so much.

**Comment by delbaoliveira** [comment]
Hi @XahidEx, could you tell me more about the error you're having?

**Comment by shamwela** [comment]
I think he meant that your production builds failed.

**Comment by delbaoliveira** [comment]
Probably to do with not adding environment variables, you can see what needs adding here:

https://github.com/delbaoliveira/website/blob/main/.env.example
