### ISSUE TITLE
How did you achieve the grainy texture on the background?

### ISSUE THREAD

**Issue by jdboachie** [delbaoliveira/website#43]
I noticed the background texture is separate from the gradient image (right?). How did you do it? Can't seem to find it in your code.

**Comment by ericlingithub** [comment]
This svg does the trick.
https://github.com/delbaoliveira/website/blob/06a5b72aebc8b5b1e5b6f6d09198d9886f7623dd/app/layout.tsx#L60

**Comment by jdboachie** [comment]
Thanks!
