### ISSUE TITLE
Do you plan integrate dark-mode ?

### ISSUE THREAD

**Issue by markozxuu** [delbaoliveira/website#6]
Hi Delba 👋 Your site is amazing ! In my site also use Next.js. In case that You plan to integrate dark mode in your site, I recommend [next-themes](https://github.com/pacocoursey/next-themes) package 😄  👍

**Comment by delbaoliveira** [comment]
Thank you for the suggestion Markoz, I've been thinking about adding dark mode. Will take a look at the package :)

**Comment by swarup4741** [comment]
Hi Delba 👋 can i fork your project and a try a dark mode on it if you don't mind ?
 I will show you my result asap ...
