### ISSUE TITLE
Found bug

### ISSUE THREAD

**Issue by theodorusclarence** [delbaoliveira/website#9]
Hey Delba, solid work on the Like Button! I found a bug on your site, and I think you should fix it. 

How can I contact you for the bug details? I don't think posting here publicly is a great idea

**Comment by delbaoliveira** [comment]
Hey! 

No worries, feel free to post it here. I think I know what you're talking about, it's a race condition bug when someone rapidly likes the button for the first time. 

I'm going to move DBs soon and will probably solve it then. But if you have more insight, would love to hear it. :)

**Comment by theodorusclarence** [comment]
https://github.com/delbaoliveira/website/blob/main/pages/api/likes/%5Bid%5D.ts#L55

Its in your likes api, you should constrain it to only 1-3 likes for now, and maybe if the likeByUser is already maxed out, you need to throw an error.

By accessing straight through API, I can basically add whatever amount to your likes, also decrement your likes.

I followed similiar structure as your like api, but using FaunaDB, maybe you want to [check my repo out](https://github.com/theodorusclarence/theodorusclarence.com)

Good luck! 🚀

**Comment by theodorusclarence** [comment]
![delba](https://user-images.githubusercontent.com/55318172/126363155-0708b91f-d421-47bf-b9b6-a6f25b32e50c.gif)
